config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :entries do
    member do
      post :add
      delete :remove
    end
    collection do
      get :progress
    end

  end
  root 'entries#index'

  resources :redoxtest, defaults: {format: :json} do
    member do
      get :redox
      post :redox
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
# == Schema Information
#
# Table name: entries
#
#  id                     :integer          not null, primary key
#  date                   :datetime
#  pain                   :integer
#  diary                  :text
#  medtype                :string
#  activity               :integer
#  doses                  :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  confirmed              :string
#  user_id                :integer
#  anger                  :float
#  disgust                :float
#  fear                   :float
#  joy                    :float
#  sadness                :float
#

class Entry < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :user

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  opdate                 :datetime
#  comorbids              :string           default([]), is an Array
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
require 'httparty'
require 'watson-api-client'
require 'uri'
class EntriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @entries = current_user.entries
  end

  def new
    @entry = Entry.new
    @entry.confirmed = "no"
  end

  def create
    entry = Entry.new(entry_params)
    if entry.pain != nil && entry.diary != nil && entry.activity != nil && entry.doses != nil
      entry.confirmed = "yes"
    end
    if entry.confirmed = "yes"
      current_user.entries << entry
    end

    #analyze tone
    text = URI.encode(entry.diary)
    result = HTTParty.get("https://gateway.watsonplatform.net/tone-analyzer/api/v3/tone?version=2016-05-19&text=" + text, basic_auth: {username: '8c6b8182-d632-40c1-be29-1505163009f8', password: 'yhmdb5Z5vwOZ'})
    tones = result["document_tone"]["tone_categories"][0]["tones"]
    total = 0.0
    if Entry.last == nil
      entry.panger = 0.0
      entry.pdisgust = 0.0
      entry.pfear = 0.0
      entry.psadness = 0.0
      entry.pjoy = 0.0
    else
      entry.panger = Entry.last.anger
      entry.pdisgust = Entry.last.disgust
      entry.pfear = Entry.last.fear
      entry.psadness = Entry.last.sadness
      entry.pjoy = Entry.last.joy
    end

    tones.each do |t|
      if t["tone_id"] == "anger"
        entry.anger = t["score"]
        total = total + entry.anger
      elsif t["tone_id"] == "disgust"
        entry.disgust = t["score"]
        total = total + entry.disgust
      elsif t["tone_id"] == "fear"
        entry.fear = t["score"]
        total = total + entry.fear
      elsif t["tone_id"] == "joy"
        entry.joy = t["score"]
        total = total + entry.joy
      elsif t["tone_id"] == "sadness"
        entry.sadness = t["score"]
        total = total + entry.sadness
      end
    end
    entry.anger = (entry.anger / total) * 100
    entry.fear = (entry.fear / total) * 100
    entry.sadness = (entry.sadness / total) * 100
    entry.joy = (entry.joy / total) * 100
    entry.disgust = (entry.disgust / total) * 100
    entry.save
    redirect_to '/entries'
  end

  def remove
    Entry.destroy(params[:id])
    redirect_to '/entries'
  end

  def show
  end

  def progress
  end

  private
    def entry_params
      params.require(:entry).permit(:id, :pain, :diary, :activity, :doses, :medtype, :user_id, :created_at, :confirmed)
    end
end

app/controllers/redoxtest_controller.rb
class RedoxtestController < ApplicationController
  skip_before_action :verify_authenticity_token
  respond_to :json
  def index
    @querystring = request.env["QUERY_STRING"]
    @challenge = @querystring[10..-1]
    @verification = request.headers["HTTP_VERIFICATION_TOKEN"]
    if @verification == 'blockcare'
      render plain: @challenge
    end
  end

  def create
    @jsonobj = request.params["Meta"]["DataModel"]
  end

  def redox

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/redoxtest_helper.rb
module RedoxtestHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,500,700,900" rel="stylesheet">
    <title>Index</title>
    <!-- Sets initial viewport load and disables zooming  -->
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- Makes your prototype chrome-less once bookmarked to your phone's home screen -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- <link href="ratchet.css" rel="stylesheet">
    <script src="ratchet.js"></script>
    <link href="custom.css" rel="stylesheet"> -->
  </head>
  <body style="background-color:#3fa9f5; font-family:Lato">
    <br></br>
    <div class="content">
      <!-- Title Text -->
      <div class="content-padded">
        <h1 class="enter" align = "center" style="color:white">WellSoon</h1>
      </div>
      <br></br><br></br>
      <!-- Creating buttons for transitions to sign up and log in pages -->
      <div align="center">
        <a class="btn btn-positive btn-block" id="nav" href="/entries/new" style="text-decoration:none; color:white">
          New Entry
        </a>
          <br></br>
        <a class="btn btn-positive btn-block" id="nav" href="/entries/progress" style="text-decoration:none; color:white">
          View Progress
        </a>
      </div>

    </div>
    <br></br>
    <% if @entries.first != nil %>
      <% @entries.each do |e| %>
        <div align="middle" style="background:white; margin-left:10%; margin-right:10%; border:2px solid black">
          <p>Date: <%= e.created_at.strftime("%m/%d/%Y at %I:%M%p %Z") %></p>
          <p>Pain level: <%= e.pain %>/10</p>
          <p>Activity level: <%= e.activity %>/5</p>
          <p>Dosage taken: <%= e.doses %> pills</p>
          <p style="font-weight:bold">-Journal-</p>
          <%= e.diary %>
          <br></br>
          
            <p>Anger: <%= e.anger.round %> %</p>
            <p>Disgust: <%= e.disgust.round %> %</p>
            <p>Fear: <%= e.fear.round %> %</p>
            <p>Sadness: <%= e.sadness.round %> %</p>
            <p>Joy: <%= e.joy.round %> %</p>

          <br></br>
          <%= button_to "Delete", remove_entry_path(id: e.id),
             {
              :method => :delete,
              :style => "padding-bottom: 25px;"
             } %>
          <br></br>
        </div>
      <% end %>
    <% end %>
  </body>
</html>

app/views/entries/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,500,700,900" rel="stylesheet">
    <title>Index</title>
    <!-- Sets initial viewport load and disables zooming  -->
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- Makes your prototype chrome-less once bookmarked to your phone's home screen -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- <link href="ratchet.css" rel="stylesheet">
    <script src="ratchet.js"></script>
    <link href="custom.css" rel="stylesheet"> -->
  </head>
  <body style="background-color:#3fa9f5; font-family:Lato">
    <br></br>
  <div class="content">
      <!-- Title Text -->
       <div class="content-padded">
          <h1 class="enter" align = "center" style="color:white">New Entry</h1>
        </div>
      <br></br><br></br>

       <!-- Creating buttons for transitions to sign up and log in pages -->
      <div class="form" align="center">
      <%= form_for(@entry) do |f| %>
        <%= f.number_field :pain, :placeholder => "Pain from 1 to 10" %>
        <br></br>
        <%= f.number_field :activity, :placeholder => "Activity from 1 to 5" %>
        <br></br>
        <%= f.number_field :doses, :placeholder => "Number of pills taken" %>
        <br></br>
        <%= f.text_field :diary, :placeholder => "Describe your day" %>
        <div class="blue-bg" style="height: 50px; color: white: font-size: 20px;">
          <div style="height:7px;"></div>
          <span class="blue-bg" style="padding-top: 5px; font-size: 20px;">
            <%= f.submit "Next" %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WellSoon</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">

  <!-- Sets initial viewport load and disables zooming  -->
  <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">

  <!-- Makes your prototype chrome-less once bookmarked to your phone's home screen -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

  <!-- Set Apple icons for when prototype is saved to home screen -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="touch-icons/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="touch-icons/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon-precomposed" sizes="57x57" href="touch-icons/apple-touch-icon-57x57.png">
</head>
<body>

  <!-- Make sure all your bars are the first things in your <body> -->
  <header class="bar-title">
  </header>

  <!-- Wrap all non-bar HTML in the .content div (this is actually what scrolls) -->
  <div class="content">
    <%= yield %>
  </div>
</body>
</html>

app/views/redoxtest/create.html.erb
<p> this is the create </p>